version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: airport-container
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airport_network

volumes:
  postgres_data:

networks:
  airport_network:
    name: airport_network
